application: guperf
version: 1-4
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /c
  static_dir: c

- url: /j
  static_dir: j

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: .*
  script: main.py
